server {
    listen 80;
    server_name 178.104.245.26; # Cambia con il tuo dominio se ne hai uno
    client_max_body_size 50M;

    # Frontend - Next.js
    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Backend API - Node.js
    location /api {
        proxy_pass http://127.0.0.1:5001/api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Discord Auth Callbacks
    location /auth {
        proxy_pass http://127.0.0.1:5001/auth;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
